### ISSUE TITLE
Informação descritiva em cada operação

### ISSUE THREAD

**Issue by tomas99batista** [Self-Service-Campus/ssc-webapp#65]

**Comment by tomas99batista** [comment]
'Descrição' onde jutificavas as alterações realizadas para quando fosses aos logs, pudesses ver a razão de tal alteração

**Comment by Diaj3** [comment]
**DONE**: Added description for main tasks, only _delete_ action is left to do. Also added some extra steps for important tasks such as _delete_ . + some design stuff

**TODO**: Problem found: Logs disappear whenever the associated switch is deleted

**CURRENTLY WORKING ON**: The problem above

**Comment by Diaj3** [comment]
**DONE**: _Add_, _Enable_/_Disable_ and _Delete_ have an action description, the others do not since they are fairly trivial so having a description would have been overkill. The logs are also completed and even when switches are deleted the log will still keep every bit of info they originally had.
